### ISSUE TITLE
Bug in the org filter sql generation

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/WDK#20]
ryan said: "Bug in the org filter sql generation."

cristina emailed: 
i think this is suspicious..  the SQL has a
FROM (null) f) 

cant reproduce:
https://tritrypdb.org/tritrypdb/app/workspace/strategies/import/a60161bccf535022
(strategy of the user below)

Begin forwarded message:

From: [tomcat@tritrypdb.org](mailto:tomcat@tritrypdb.org)
Subject: TriTrypDB Service Error - 170.84.47.133
Date: April 23, 2022 at 2:12:22 PM EDT
To: [aurreco@uga.edu](mailto:aurreco@uga.edu), [epharper@upenn.edu](mailto:epharper@upenn.edu), [dfalke@uga.edu](mailto:dfalke@uga.edu), [rdoherty@upenn.edu](mailto:rdoherty@upenn.edu), [sfischer@pcbi.upenn.edu](mailto:sfischer@pcbi.upenn.edu), [jtlong@upenn.edu](mailto:jtlong@upenn.edu), [robert.belnap@uga.edu](mailto:robert.belnap@uga.edu)

[EXTERNAL SENDER - PROCEED CAUTIOUSLY]

##ERROR_START##
Matched Filter: null

************************************************
Date: 2022-04-23T14:12:22.896
Request URI: [https://tritrypdb.org/tritrypdb](https://urldefense.com/v3/__https://tritrypdb.org/tritrypdb__;!!IBzWLUs!X2IAmwKu7GPJHRShLp_IiBkiNmsMRbDHn5WQY6fw6d7g9cRM8Ey6o00qEOQqzzwPQHeRdjC38lLucXlUZQ$)
Remote Host: 170.84.47.133
Referred from: [https://tritrypdb.org/tritrypdb/app/workspace/strategies/325321023/428253153](https://urldefense.com/v3/__https://tritrypdb.org/tritrypdb/app/workspace/strategies/325321023/428253153__;!!IBzWLUs!X2IAmwKu7GPJHRShLp_IiBkiNmsMRbDHn5WQY6fw6d7g9cRM8Ey6o00qEOQqzzwPQHeRdjC38lIH3eklog$)
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
Server Addr: <not set> Is 'JkEnvVar SERVER_ADDR' set in the Apache configuration?
Server Name: [tritrypdb.org](https://urldefense.com/v3/__http://tritrypdb.org/__;!!IBzWLUs!X2IAmwKu7GPJHRShLp_IiBkiNmsMRbDHn5WQY6fw6d7g9cRM8Ey6o00qEOQqzzwPQHeRdjC38lKj1I6OqQ$)
Session ID: 79467
Request ID: 111332
Request duration at error: 37935ms
Date of last webapp reload: 2022-04-21T12:27:32.378
Time since last webapp reload: 49:44:50.518
Log4j Marker: 32f41aab-bbbf-4849-8e11-5271c83c732d

************************************************
Project ID: TriTrypDB
User DB: webwww@jdbc:oracle:oci:@apicommS | Connections: Active { max=20, current=0 }, Idle { range=[1..10], current=9 }
App DB: webwww@jdbc:oracle:oci:@tryp057s | Connections: Active { max=20, current=3 }, Idle { range=[1..1], current=1 }

************************************************
Request Parameters (query string or posted form data)

************************************************
Associated Request-Scope Attributes

org.glassfish.jersey.message.internal.TracingLogger = org.glassfish.jersey.message.internal.TracingLogger$1@4c05087f
javax.servlet.request.ssl_session = 02885d609f422ba9b7aabc1448df9a646866bd058c2ced1ff2d50366241dbbd6
javax.servlet.request.cipher_suite = ECDHE-RSA-AES256-GCM-SHA384
omitRequestLogging = false
javax.servlet.request.key_size = 256

************************************************
Session Attributes

wdk_user = User #319224480 - [alejo.prego@gmail.com](mailto:alejo.prego@gmail.com)

************************************************
Detailed Description

java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.gusdb.wdk.model.WdkModelException: Unable to create cache.
       at org.gusdb.fgputil.functional.Functions.mapException(Functions.java:516)
       at org.gusdb.fgputil.functional.Functions.wrapException(Functions.java:528)
       at org.gusdb.wdk.model.columntool.byvalue.reporter.AbstractByValueReporter.getRecordCount(AbstractByValueReporter.java:92)
       at org.gusdb.fgputil.distribution.AbstractDistribution.generateDistribution(AbstractDistribution.java:55)
       at org.gusdb.wdk.model.columntool.byvalue.reporter.AbstractByValueReporter.report(AbstractByValueReporter.java:126)
       at org.gusdb.wdk.service.service.AnswerService.lambda$getAnswerAsStream$5(AnswerService.java:467)
       at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:78)
       at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:60)
       at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
       at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
       at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
       at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106)
       at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
       at org.gusdb.wdk.service.filter.RequestLoggingFilter.aroundWriteTo(RequestLoggingFilter.java:150)
       at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
       at org.gusdb.wdk.service.filter.LoggingContextFilter.aroundWriteTo(LoggingContextFilter.java:49)
       at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
       at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:86)
       at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
       at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
       at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)
       at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)
       at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)
       at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)
       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
       at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
       at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
       at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
       at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
       at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
       at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
       at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
       at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
       at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
       at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
       at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
       at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
       at org.eupathdb.common.controller.ProjectIdMacroFilter.doFilter(ProjectIdMacroFilter.java:39)
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
       at org.eupathdb.common.controller.BetaLegacyFilter.doFilter(BetaLegacyFilter.java:53)
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
       at org.gusdb.wdk.controller.filter.HttpResponseHeaderLogger.doFilter(HttpResponseHeaderLogger.java:49)
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
       at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:223)
       at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:311)
       at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:793)
       at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:722)
       at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:915)
       at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
       at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: org.gusdb.wdk.model.WdkModelException: Unable to create cache.
       at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
       at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
       at org.gusdb.wdk.model.columntool.byvalue.reporter.AbstractByValueReporter.lambda$getRecordCount$1(AbstractByValueReporter.java:92)
       at org.gusdb.fgputil.functional.Functions.mapException(Functions.java:513)
       ... 66 more
Caused by: org.gusdb.wdk.model.WdkModelException: Unable to create cache.
       at org.gusdb.wdk.model.query.SqlQueryInstance.createCacheTableAndInsertResult(SqlQueryInstance.java:99)
       at org.gusdb.wdk.model.dbms.ResultFactory.createCache(ResultFactory.java:98)
       at org.gusdb.wdk.model.dbms.ResultFactory.cacheResults(ResultFactory.java:73)
       at org.gusdb.wdk.model.query.QueryInstance.getInstanceInfo(QueryInstance.java:137)
       at org.gusdb.wdk.model.query.QueryInstance.getCachedSql(QueryInstance.java:236)
       at org.gusdb.wdk.model.query.SqlQueryInstance.getSql(SqlQueryInstance.java:57)
       at org.gusdb.wdk.model.query.SqlQueryInstance.getSqlUnsorted(SqlQueryInstance.java:52)
       at org.gusdb.wdk.model.answer.AnswerValue.getBaseIdSql(AnswerValue.java:667)
       at org.gusdb.wdk.model.answer.AnswerValue.getIdSql(AnswerValue.java:680)
       at org.gusdb.wdk.model.answer.AnswerValue.getIdSql(AnswerValue.java:663)
       at org.gusdb.wdk.model.record.DefaultResultSizePlugin.getResultSize(DefaultResultSizePlugin.java:18)
       at org.gusdb.wdk.model.answer.ResultSizeFactory.getResultSize(ResultSizeFactory.java:70)
       at org.gusdb.wdk.model.columntool.byvalue.reporter.AbstractByValueReporter.lambda$setAnswerValue$0(AbstractByValueReporter.java:80)
       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
       ... 1 more
Caused by: java.sql.SQLException: Failed to run SQL (name=InternalQueries.bq_TranscriptRecordClasses_TranscriptRecordClass__create-cache-table):
CREATE TABLE QueryResult984 AS SELECT 984 AS wdk_instance_id, rownum AS wdk_row_id,  f.* FROM (SELECT DISTINCT gene_source_id, source_id, project_id, sum(wdk_weight) as wdk_weight, max(left_match) as left_match, max(right_match) as right_match FROM (
-- boolean of genes
WITH genes as (SELECT gene_source_id, project_id, sum (wdk_weight) AS wdk_weight FROM ((SELECT 1 AS wdk_t, ls.* FROM (select gene_source_id, project_id, max(wdk_weight) as wdk_weight from (SELECT wdk_weight, gene_source_id, project_id FROM (null) f) l group by gene_source_id, project_id) ls) UNION (SELECT 2 AS wdk_t, rs.* FROM (select gene_source_id, project_id, max(wdk_weight) as wdk_weight from (SELECT wdk_weight, gene_source_id, project_id FROM (null) f) r group by gene_source_id, project_id) rs)) t GROUP BY gene_source_id, project_id HAVING count(*) > 1)
-- major select
select gene_source_id, source_id, project_id, wdk_weight, decode(sum(left_match), 1, 'Y', 0, 'N') as left_match, decode(sum(right_match), 1, 'Y', 0, 'N') as right_match
from (
 select left.gene_source_id, left.source_id, left.project_id, genes.wdk_weight, 1 as left_match, 0 as right_match
 from genes,
 (SELECT wdk_weight, gene_source_id, source_id, project_id FROM ((

 /* new filter applied on id query */
 select * from (select idsql.* from (SELECT * FROM QueryResult985 ORDER BY wdk_row_id ASC ) idsql, (
 /* answer param value cols applied on id query */

 /* the ID query */
 SELECT * FROM QueryResult985) filteredIdSql where  idsql.gene_source_id = filteredIdSql.gene_source_id  AND  idsql.source_id = filteredIdSql.source_id  AND  idsql.project_id = filteredIdSql.project_id ) WHERE 1 = 0 OR (left_match= 'Y' AND right_match= 'Y')
)) f) left
 where left.gene_source_id = genes.gene_source_id
 UNION
 select right.gene_source_id, right.source_id, right.project_id, genes.wdk_weight, 0 as left_match, 1 as right_match
 from genes,
 (SELECT wdk_weight, gene_source_id, source_id, project_id FROM ((

 /* new filter applied on id query */
 select * from (select idsql.* from (SELECT * FROM QueryResult959 ORDER BY wdk_row_id ASC ) idsql, (
 /* answer param value cols applied on id query */

 /* the ID query */
 SELECT * FROM QueryResult959) filteredIdSql where  idsql.gene_source_id = filteredIdSql.gene_source_id  AND  idsql.source_id = filteredIdSql.source_id  AND  idsql.project_id = filteredIdSql.project_id ) WHERE 1 = 0  OR matched_result= 'Y'
)) f) right
 where right.gene_source_id = genes.gene_source_id
 UNION
 select ta.gene_source_id, ta.source_id, genes.project_id, genes.wdk_weight, 0 as left_match, 0 as right_match
 from genes, apidbtuning.transcriptattributes ta
 where genes.gene_source_id = ta.gene_source_id) big
group by (gene_source_id, source_id, project_id, wdk_weight)) group by (gene_source_id, source_id, project_id)) f
Connect URL: jdbc:oracle:oci:@tryp057s
User: WEBWWW
       at org.gusdb.fgputil.db.SqlUtils.executeUpdate(SqlUtils.java:284)
       at org.gusdb.wdk.model.query.SqlQueryInstance.createCacheTableAndInsertResult(SqlQueryInstance.java:94)
       ... 16 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-00903: invalid table name

       at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1136)
       at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1039)
       at oracle.jdbc.driver.T2CStatement.executeForDescribe(T2CStatement.java:920)
       at oracle.jdbc.driver.T2CStatement.executeForRows(T2CStatement.java:1163)
       at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
       at oracle.jdbc.driver.OracleStatement.executeUpdateInternal(OracleStatement.java:1661)
       at oracle.jdbc.driver.OracleStatement.executeLargeUpdate(OracleStatement.java:1626)
       at oracle.jdbc.driver.OracleStatement.executeUpdate(OracleStatement.java:1613)
       at oracle.jdbc.driver.OracleStatementWrapper.executeUpdate(OracleStatementWrapper.java:282)
       at org.apache.commons.dbcp2.DelegatingStatement.executeUpdate(DelegatingStatement.java:322)
       at org.apache.commons.dbcp2.DelegatingStatement.executeUpdate(DelegatingStatement.java:322)
       at org.gusdb.fgputil.db.wrapper.AbstractStatementWrapper.executeUpdate(AbstractStatementWrapper.java:49)
       at org.gusdb.fgputil.db.SqlUtils.executeUpdate(SqlUtils.java:279)
       ... 17 more
Caused by: Error : 903, Position : 515, Sql = CREATE TABLE QueryResult984 AS SELECT 984 AS wdk_instance_id, rownum AS wdk_row_id,  f.* FROM (SELECT DISTINCT gene_source_id, source_id, project_id, sum(wdk_weight) as wdk_weight, max(left_match) as left_match, max(right_match) as right_match FROM (
-- boolean of genes
WITH genes as (SELECT gene_source_id, project_id, sum (wdk_weight) AS wdk_weight FROM ((SELECT 1 AS wdk_t, ls.* FROM (select gene_source_id, project_id, max(wdk_weight) as wdk_weight from (SELECT wdk_weight, gene_source_id, project_id FROM (null) f) l group by gene_source_id, project_id) ls) UNION (SELECT 2 AS wdk_t, rs.* FROM (select gene_source_id, project_id, max(wdk_weight) as wdk_weight from (SELECT wdk_weight, gene_source_id, project_id FROM (null) f) r group by gene_source_id, project_id) rs)) t GROUP BY gene_source_id, project_id HAVING count(*) > 1)
-- major select
select gene_source_id, source_id, project_id, wdk_weight, decode(sum(left_match), 1, 'Y', 0, 'N') as left_match, decode(sum(right_match), 1, 'Y', 0, 'N') as right_match
from (
 select left.gene_source_id, left.source_id, left.project_id, genes.wdk_weight, 1 as left_match, 0 as right_match
 from genes,
 (SELECT wdk_weight, gene_source_id, source_id, project_id FROM ((

 /* new filter applied on id query */
 select * from (select idsql.* from (SELECT * FROM QueryResult985 ORDER BY wdk_row_id ASC ) idsql, (
 /* answer param value cols applied on id query */

 /* the ID query */
 SELECT * FROM QueryResult985) filteredIdSql where  idsql.gene_source_id = filteredIdSql.gene_source_id  AND  idsql.source_id = filteredIdSql.source_id  AND  idsql.project_id = filteredIdSql.project_id ) WHERE 1 = 0 OR (left_match= 'Y' AND right_match= 'Y')
)) f) left
 where left.gene_source_id = genes.gene_source_id
 UNION
 select right.gene_source_id, right.source_id, right.project_id, genes.wdk_weight, 0 as left_match, 1 as right_match
 from genes,
 (SELECT wdk_weight, gene_source_id, source_id, project_id FROM ((

 /* new filter applied on id query */
 select * from (select idsql.* from (SELECT * FROM QueryResult959 ORDER BY wdk_row_id ASC ) idsql, (
 /* answer param value cols applied on id query */

 /* the ID query */
 SELECT * FROM QueryResult959) filteredIdSql where  idsql.gene_source_id = filteredIdSql.gene_source_id  AND  idsql.source_id = filteredIdSql.source_id  AND  idsql.project_id = filteredIdSql.project_id ) WHERE 1 = 0  OR matched_result= 'Y'
)) f) right
 where right.gene_source_id = genes.gene_source_id
 UNION
 select ta.gene_source_id, ta.source_id, genes.project_id, genes.wdk_weight, 0 as left_match, 0 as right_match
 from genes, apidbtuning.transcriptattributes ta
 where genes.gene_source_id = ta.gene_source_id) big
group by (gene_source_id, source_id, project_id, wdk_weight)) group by (gene_source_id, source_id, project_id)) f, OriginalSql = CREATE TABLE QueryResult984 AS SELECT 984 AS wdk_instance_id, rownum AS wdk_row_id,  f.* FROM (SELECT DISTINCT gene_source_id, source_id, project_id, sum(wdk_weight) as wdk_weight, max(left_match) as left_match, max(right_match) as right_match FROM (
-- boolean of genes
WITH genes as (SELECT gene_source_id, project_id, sum (wdk_weight) AS wdk_weight FROM ((SELECT 1 AS wdk_t, ls.* FROM (select gene_source_id, project_id, max(wdk_weight) as wdk_weight from (SELECT wdk_weight, gene_source_id, project_id FROM (null) f) l group by gene_source_id, project_id) ls) UNION (SELECT 2 AS wdk_t, rs.* FROM (select gene_source_id, project_id, max(wdk_weight) as wdk_weight from (SELECT wdk_weight, gene_source_id, project_id FROM (null) f) r group by gene_source_id, project_id) rs)) t GROUP BY gene_source_id, project_id HAVING count(*) > 1)
-- major select
select gene_source_id, source_id, project_id, wdk_weight, decode(sum(left_match), 1, 'Y', 0, 'N') as left_match, decode(sum(right_match), 1, 'Y', 0, 'N') as right_match
from (
 select left.gene_source_id, left.source_id, left.project_id, genes.wdk_weight, 1 as left_match, 0 as right_match
 from genes,
 (SELECT wdk_weight, gene_source_id, source_id, project_id FROM ((

 /* new filter applied on id query */
 select * from (select idsql.* from (SELECT * FROM QueryResult985 ORDER BY wdk_row_id ASC ) idsql, (
 /* answer param value cols applied on id query */

 /* the ID query */
 SELECT * FROM QueryResult985) filteredIdSql where  idsql.gene_source_id = filteredIdSql.gene_source_id  AND  idsql.source_id = filteredIdSql.source_id  AND  idsql.project_id = filteredIdSql.project_id ) WHERE 1 = 0 OR (left_match= 'Y' AND right_match= 'Y')
)) f) left
 where left.gene_source_id = genes.gene_source_id
 UNION
 select right.gene_source_id, right.source_id, right.project_id, genes.wdk_weight, 0 as left_match, 1 as right_match
 from genes,
 (SELECT wdk_weight, gene_source_id, source_id, project_id FROM ((

 /* new filter applied on id query */
 select * from (select idsql.* from (SELECT * FROM QueryResult959 ORDER BY wdk_row_id ASC ) idsql, (
 /* answer param value cols applied on id query */

 /* the ID query */
 SELECT * FROM QueryResult959) filteredIdSql where  idsql.gene_source_id = filteredIdSql.gene_source_id  AND  idsql.source_id = filteredIdSql.source_id  AND  idsql.project_id = filteredIdSql.project_id ) WHERE 1 = 0  OR matched_result= 'Y'
)) f) right
 where right.gene_source_id = genes.gene_source_id
 UNION
 select ta.gene_source_id, ta.source_id, genes.project_id, genes.wdk_weight, 0 as left_match, 0 as right_match
 from genes, apidbtuning.transcriptattributes ta
 where genes.gene_source_id = ta.gene_source_id) big
group by (gene_source_id, source_id, project_id, wdk_weight)) group by (gene_source_id, source_id, project_id)) f, Error Msg = ORA-00903: invalid table name

       at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1145)
       ... 29 more

-- from pageContext.getException()

##ERROR_END##

**Comment by ryanrdoherty** [comment]
@aurreco-uga, I'm looking at the null subquery issue with org param.  Wondering if we've seen any of these since we patched the DB, converting column name 'organism' to 'organism_full'?

I can't quite figure out what is going on.  The null is the internal value of an AnswerParam in the boolean.  In the SQL, both left and right sides are being assigned null.  It's as if the internal values of the answer params are not being put in the internal value map for the boolean query.  But that seems far fetched- I can't see how that could happen.  Maybe what I'll do is put some logging in so we can diagnose this better the next time it happens (if it happens again)?

The other possibility is that there's some sort of race condition going on.  If you recall, the column filter reporter requires a result size, but waiting for the result size to compute the value distribution was costing us precious seconds.  So I parallelized the calls to run concurrently.  I thought maybe if the result was not already in the cache, this might make two separate caches and cause issues.  But I tried a few things where I made a 2-step (3 with boolean) strategy with various org filter applications, then cleared the cache and visited the boolean.  Didn't have any problems.  Hard to diagnose when we can't recreate.

So I was thinking maybe it had to do with the invalid filter name.  We still don't validate column filter configs the same way we do params and other filters.  So we might be assuming that something is valid up front, then it sneaks in and causes the null later on.  I have a long-standing TODO to make column filters Validateable in the same way params and step filters are.  When Ellie first wrote column filters, she didn't do it and I've wanted to backfill since then, but have not had time/priority.

**Comment by ryanrdoherty** [comment]
Added [this commit](https://github.com/VEuPathDB/WDK/commit/52aff7d8393718ae74d9fb8d738e1319025d901a) to master and api-build-57 branches.

**Comment by ryanrdoherty** [comment]
Analysis of a second error email revealed that probably have a race condition between the two running threads (result size count and distribution calculation), which were sharing a stateful instance of AnswerValue.  [This commit ](https://github.com/VEuPathDB/WDK/commit/4758ac898bff7bca03f6db7475b3ce742d6bf9b5)hopefully fixes the issue by making a copy of the AnswerValue up front so the threads have their own copies.  I also ensured that the spawned thread is reclaimed once it completes its work.

**Comment by ryanrdoherty** [comment]
Had to go back and fix this again because I didn't clone the query instance inside the AnswerValue (so the non-threadsafe object was still shared).  This commit fixes: https://github.com/VEuPathDB/WDK/commit/1c956b43c9a5d050475e48dd07417dbdc948900d
