### ISSUE TITLE
User datasets: closing the DSSession hangs if the installer ran too long

### ISSUE THREAD

**Issue by wbazant** [VEuPathDB/WDK#7]
https://github.com/VEuPathDB/WDK/blob/master/Model/src/main/java/org/gusdb/wdk/model/user/dataset/event/UserDatasetEventHandler.java#L98
This happened in the Jenkins job:
```
Time: around 18:00
571010 [INFO ] org.gusdb.wdk.model.user.dataset.event.UserDatasetEventHandler:195 - Start handling event: 159561602100014395
575392 [INFO ] org.gusdb.wdk.model.user.dataset.UserDatasetTypeHandler:119 - Running command: installBiomUserDataset 18398 /var/tmp/wdk/ud_18398_18044976547433378208/metadata.json /var/tmp/wdk/ud_18398_18044976547433378208/data.tsv MicrobiomeDB
Time: around 19:00
5675967 [INFO ] org.gusdb.wdk.model.user.dataset.event.UserDatasetEventHandler:166 - Granting access to user dataset 18398 to user 875510 in table UserDatasetOwner
```
and then the job hung. I've asked the VM for a stack trace and got:

```
"main" #1 prio=5 os_prio=0 cpu=13160.80ms elapsed=11076.19s tid=0x00007f6324018800 nid=0x62c5 runnable  [0x00007f632c752000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@11.0.6/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@11.0.6/SocketInputStream.java:115)
	at java.net.SocketInputStream.read(java.base@11.0.6/SocketInputStream.java:168)
	at java.net.SocketInputStream.read(java.base@11.0.6/SocketInputStream.java:140)
	at sun.security.ssl.SSLSocketInputRecord.read(java.base@11.0.6/SSLSocketInputRecord.java:448)
	at sun.security.ssl.SSLSocketInputRecord.decode(java.base@11.0.6/SSLSocketInputRecord.java:165)
	at sun.security.ssl.SSLTransport.decode(java.base@11.0.6/SSLTransport.java:108)
	at sun.security.ssl.SSLSocketImpl.decode(java.base@11.0.6/SSLSocketImpl.java:1151)
	at sun.security.ssl.SSLSocketImpl.waitForClose(java.base@11.0.6/SSLSocketImpl.java:1412)
	at sun.security.ssl.SSLSocketImpl.closeSocket(java.base@11.0.6/SSLSocketImpl.java:1388)
	at sun.security.ssl.SSLSocketImpl.shutdown(java.base@11.0.6/SSLSocketImpl.java:1369)
	at sun.security.ssl.SSLSocketImpl.bruteForceCloseInput(java.base@11.0.6/SSLSocketImpl.java:603)
	at sun.security.ssl.SSLSocketImpl.duplexCloseOutput(java.base@11.0.6/SSLSocketImpl.java:566)
	at sun.security.ssl.SSLSocketImpl.close(java.base@11.0.6/SSLSocketImpl.java:479)
	at org.irods.jargon.core.connection.IRODSBasicTCPConnection.closeDownSocketAndEatAnyExceptions(IRODSBasicTCPConnection.java:240)
	at org.irods.jargon.core.connection.IRODSBasicTCPConnection.shutdown(IRODSBasicTCPConnection.java:258)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.shutdown(AbstractIRODSMidLevelProtocol.java:828)
	- locked <0x00000000afc0d810> (a org.irods.jargon.core.connection.IRODSMidLevelProtocol)
	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.returnIRODSProtocol(IRODSSimpleProtocolManager.java:92)
	at org.irods.jargon.core.connection.IRODSSession.closeSession(IRODSSession.java:255)
	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.closeSessionAndEatExceptions(IRODSAccessObjectFactoryImpl.java:154)
	at org.gusdb.wdk.model.user.dataset.irods.IrodsUserDatasetStoreAdaptor.close(IrodsUserDatasetStoreAdaptor.java:370)
	at org.gusdb.wdk.model.user.dataset.irods.IrodsUserDatasetSession.close(IrodsUserDatasetSession.java:80)
	at org.gusdb.wdk.model.user.dataset.event.UserDatasetEventHandler.handleInstallEvent(UserDatasetEventHandler.java:99)
	at org.gusdb.wdk.model.user.dataset.event.UserDatasetEventArrayHandler.handleEventList(UserDatasetEventArrayHandler.java:93)
	at org.apidb.irods.BuildEventsFile.main(BuildEventsFile.java:93)
```

So, it's hanging at the end of the try-with-resources block, here: https://github.com/VEuPathDB/WDK/blob/master/Model/src/main/java/org/gusdb/wdk/model/user/dataset/event/UserDatasetEventHandler.java#L98

My understanding of the issue is that the session is open for too long, and that's why it hangs when closing. The solution would involve reworking the code currently in `UserDatasetEventHandler.java` and the method `installInAppDb` in `UserDatasetTypeHandler.java`.

Currently, `installInAppDb` does a bunch of things it needs the `DSSession` for, then the external install which can take a while but not requiring the DSSession, and then closes the session.

I think the problem would go away if the DSSession were closed before the external install.

I have some unelegant ideas for how to change this code- move the whole of `UserDatasetTypeHandler` into `UserDatasetEventHandler`, make installInAppDb return a subroutine, require installInAppDb close the DSSession - but no good ideas really.

**Comment by wbazant** [comment]
Closing twice should be okay https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/connection/IRODSBasicTCPConnection.java#L234

**Comment by wbazant** [comment]
Also, remarkably, the connection eventually did get closed, after 24 hours:

```
92076432 [DEBUG] org.gusdb.fgputil.db.DataSourceWrapper:130 - Opening connection associated with stacktrace hash 067f3554c8033b02ae101d4b872c24ac : Connection to APP, open for 0.003 seconds, retrieved from pool at 2020-07-25T19:33:31.529
92076500 [DEBUG] org.gusdb.fgputil.db.DataSourceWrapper:143 - Closing connection associated with stacktrace hash 067f3554c8033b02ae101d4b872c24ac : Connection to APP, open for 0.071 seconds, retrieved from pool at 2020-07-25T19:33:31.529
```

after which the other datasets got processed okay, before failing on something new.

**Comment by wbazant** [comment]
Didn't help, still hangs after a large dataset.

**Comment by wbazant** [comment]
Vaguely went away. Closing for now.
